# Generated by Django 5.2.4 on 2026-05-10 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('raw_payload', models.TextField(blank=True)),
                ('lead_created', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('duplicate', 'Duplicate (Skipped)'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook Lead Ads)'), ('indiamart', 'IndiaMart'), ('justdial', 'JustDial'), ('whatsapp', 'WhatsApp Business API')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('app_id', models.CharField(blank=True, help_text='Meta App ID (used by Meta Lead Ads & WhatsApp)', max_length=200, null=True)),
                ('app_secret', models.CharField(blank=True, help_text='Meta App Secret', max_length=300, null=True)),
                ('page_access_token', models.TextField(blank=True, help_text='Meta Page Access Token with leads_retrieval permission', null=True)),
                ('verify_token', models.CharField(blank=True, help_text='Custom verify token you set when subscribing the webhook in Meta App Dashboard', max_length=200, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='WhatsApp Business Phone Number ID from Meta Dashboard', max_length=200, null=True)),
                ('whatsapp_access_token', models.TextField(blank=True, help_text='Permanent WhatsApp Cloud API Access Token', null=True)),
                ('whatsapp_verify_token', models.CharField(blank=True, help_text='Verify token for the WhatsApp webhook endpoint', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
            },
        ),
    ]
