# Generated by Django 5.0.14 on 2026-05-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_integration_models'),
        ('leads', '0002_whatsapp_models'),
    ]

    operations = [
    ]
