# Generated by Django 5.2.4 on 2026-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_integrationlog_integrationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recording_size',
            field=models.IntegerField(default=0),
        ),
    ]
