# Generated by Django 5.0.14 on 2026-05-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_merge_0002_integration_models_0002_whatsapp_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waautoreply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='keywords',
            field=models.TextField(help_text='Comma-separated keywords that trigger this rule. e.g. "price,pricing,cost,quote". Case-insensitive.'),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='lead_status_update',
            field=models.CharField(blank=True, help_text='New lead status to set (for update_lead_status action).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='match_exact',
            field=models.BooleanField(default=False, help_text='If True, full message must exactly match. If False, keyword search within message.'),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower = evaluated first'),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='reply_template',
            field=models.ForeignKey(blank=True, help_text='Template to send (for send_template action).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_reply_rules', to='leads.watemplate'),
        ),
        migrations.AlterField(
            model_name='waautoreply',
            name='reply_text',
            field=models.TextField(blank=True, help_text='Text to send (for send_text action).', null=True),
        ),
        migrations.AlterField(
            model_name='wabroadcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wabroadcast',
            name='lead_filter',
            field=models.JSONField(default=dict, help_text='Serialised filter: {"status": "interested", "source": "Meta"}. Applied at time of scheduling.'),
        ),
        migrations.AlterField(
            model_name='wabroadcast',
            name='name',
            field=models.CharField(help_text='Internal name for this broadcast', max_length=200),
        ),
        migrations.AlterField(
            model_name='wabroadcastrecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waconversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waconversation',
            name='is_opted_out',
            field=models.BooleanField(default=False, help_text='Lead sent STOP / opted out of WhatsApp messages.'),
        ),
        migrations.AlterField(
            model_name='wamessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='body_text',
            field=models.TextField(help_text='Template body. Use {{1}}, {{2}} for variables. Variable names: {{name}}, {{company}}, {{agent_name}}, {{date}}'),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text='List of button dicts. e.g. [{"type": "QUICK_REPLY", "text": "Yes"}]'),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='display_name',
            field=models.CharField(help_text='Friendly name shown in CRM', max_length=200),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='name',
            field=models.CharField(help_text='Template name as registered in Meta Business Manager (e.g. follow_up_v1)', max_length=200),
        ),
        migrations.AlterField(
            model_name='watemplate',
            name='variable_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Maps template variable positions to Lead/Agent fields.'),
        ),
    ]
