# Generated by Django 5.0.14 on 2026-05-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_waprovider_broadcast_enhancements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wabroadcast",
            name="cancelled_at",
        ),
        migrations.AlterField(
            model_name="disposition",
            name="triggers_follow_up",
            field=models.BooleanField(
                default=False,
                help_text="Prompt agent to schedule a follow-up after selecting this disposition.",
            ),
        ),
        migrations.AlterField(
            model_name="disposition",
            name="updates_lead_status",
            field=models.CharField(
                blank=True,
                help_text="Auto-update lead status to this value on submit. Leave blank for no change.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional internal notes about this campaign"
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="lead_filter",
            field=models.JSONField(
                default=dict,
                help_text='{"status": "interested", "source": "Meta", "assigned_agent_id": 5}',
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="name",
            field=models.CharField(
                help_text="Campaign name shown in dashboard", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="WhatsApp provider to use. Leave blank to use the default provider.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcasts",
                to="leads.waprovider",
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wabroadcast",
            name="text_body",
            field=models.TextField(
                blank=True,
                help_text="Plain text body. Supports {{name}}, {{company}}, {{phone}} placeholders.",
            ),
        ),
        migrations.AlterField(
            model_name="waprovider",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Used for new campaigns when no provider is selected",
            ),
        ),
        migrations.AlterField(
            model_name="waprovider",
            name="name",
            field=models.CharField(
                help_text='Friendly label, e.g. "Main Meta Account"', max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="waprovider",
            name="twilio_from_number",
            field=models.CharField(
                blank=True, help_text="Format: whatsapp:+14155238886", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="waprovider",
            name="wati_api_endpoint",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://live-mt-server.wati.io/api",
                max_length=300,
            ),
        ),
    ]
