# Generated by Django 5.0.14 on 2026-05-18 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0010_funnel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnel",
            name="agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents assigned to work leads in this funnel.",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
