# Generated by Django 5.2.4 on 2026-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='call_recording_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
