# Generated by Django 5.0.14 on 2026-05-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_dialersession_callactivityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('manager', 'Manager'), ('admin', 'Tenant Admin')], default='agent', max_length=20),
        ),
    ]
