# Generated by Django 5.0.14 on 2026-05-12 12:54

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Company / Organisation name', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner_email',
            field=models.EmailField(help_text='Primary contact email of the tenant owner', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive features are hidden from all plans globally.'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(help_text='Machine-readable key used in @require_feature decorator and Flutter feature checks. e.g. whatsapp_api', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features included in this plan.', related_name='plans', to='tenants.feature'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public plans show on the pricing page. Private plans are enterprise-only.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_agents',
            field=models.IntegerField(default=5, help_text='Maximum number of agent accounts allowed for this plan. -1 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_leads',
            field=models.IntegerField(default=1000, help_text='Maximum leads per tenant. -1 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal super-admin notes about this subscription.'),
        ),
    ]
