# Generated by Django 4.2.7 on 2026-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_remove_disposition_from_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="max_agents_override",
            field=models.IntegerField(
                blank=True,
                help_text="Custom max agent limit for this tenant. Overrides the Plan's max_agents value. Leave blank to use the Plan's limit. Set to -1 for unlimited.",
                null=True,
            ),
        ),
    ]
