# Generated by Django 5.0.14 on 2026-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsentiment',
            name='agent_talk_ratio',
            field=models.FloatField(blank=True, help_text='Fraction of call time agent spoke (0.0–1.0). Ideal: 0.3–0.5', null=True),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='customer_intent',
            field=models.CharField(blank=True, help_text='Detected intent e.g. "price inquiry", "complaint", "ready to buy"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='filler_word_count',
            field=models.IntegerField(default=0, help_text='Count of filler words (um, uh, basically, you know) in agent speech'),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='objections_detected',
            field=models.JSONField(blank=True, default=list, help_text='List of objection strings detected e.g. ["too expensive", "need to think"]'),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Score from -1.0 (very negative) to +1.0 (very positive)'),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calltranscript',
            name='language',
            field=models.CharField(default='hi', help_text='Detected language code', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='escalation_keywords',
            field=models.TextField(default='human,agent,talk to someone,speak to person,manager', help_text='Comma-separated keywords. When detected → escalate to human agent immediately.'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='max_turns_before_escalation',
            field=models.IntegerField(default=5, help_text='If bot has not qualified the lead after N turns, escalate.'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='qualification_questions',
            field=models.JSONField(default=list, help_text='List of questions to ask sequentially. e.g. ["What product are you interested in?", "What is your budget?"]'),
        ),
        migrations.AlterField(
            model_name='chatbotflow',
            name='system_prompt',
            field=models.TextField(help_text='LLM system prompt. Variables: {company_name}, {agent_name}. Define bot persona, products, escalation triggers.'),
        ),
        migrations.AlterField(
            model_name='chatbotsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='ai_urgency_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated urgency 1-10', null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, help_text='Email Message-ID header value', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='thread_id',
            field=models.CharField(blank=True, help_text='Gmail thread ID or SMTP message-ID chain root', max_length=200, null=True),
        ),
    ]
